### ISSUE TITLE
[1.0.0-Beta] Prepare first beta release

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#221]
- [x] maintain commit attribution on split
- [ ] automate changelog on each package
- [x] decide to maintain linear versioning between packages 
- [ ] Add badges to every releasable package
- [ ] Add or update minimal documentation to every releasable package

Packages to able to be versioned:
* toggle-core
* toggle-model
* inmemory-toggle
* dbal-toggle
* toggle-crud
* toggle-crud-psr7-api
* toggle-crud-psr11-factories
* symfony-toggle

Packages not ready yet:
* php-sdk
* mezzio-toggle
* laravel-toggle

Already not started packages:
* toggle-cache
* toggle-events(maybe not a package needed we can source with events core write model)
* toggle-client-api(required for distributed systems, we have to decide if provide a collection of HTTP middleware, or to implement complete async api)
