### ISSUE TITLE
[pheature-flags] Add PHP 8.1 support

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#321]
Today the PHP 8.1RC4 was released, we have to update our composer.json files to support both 7.4, 8.0, and 8.1 at least since the lowest version has support.

we can check how Laminas is applying for example for Mezzio framework:

![image](https://user-images.githubusercontent.com/1093654/137383385-96868b6b-1f50-49c9-bc56-67d4279f1510.png)

- [x] https://github.com/pheature-flags/toggle-core/issues/35
- [x] https://github.com/pheature-flags/toggle-model/issues/12
- [x] https://github.com/pheature-flags/toggle-crud/issues/13
- [x] https://github.com/pheature-flags/toggle-crud-psr11-factories/issues/14
- [x] https://github.com/pheature-flags/toggle-crud-psr7-api/issues/8
- [x] https://github.com/pheature-flags/inmemory-toggle/issues/8
- [x] https://github.com/pheature-flags/dbal-toggle/issues/6
- [x] https://github.com/pheature-flags/php-sdk/issues/6
- [x] https://github.com/pheature-flags/laravel-toggle/issues/5
- [x] https://github.com/pheature-flags/symfony-toggle/issues/13
- [x] https://github.com/pheature-flags/mezzio-toggle/issues/5
