### ISSUE TITLE
Pheature Flags Development Roadmap

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#40]
# Pheature Flags Development Roadmap

**Get full control over your application releases**

Pheature flags is a release management system that allows having full control over different features running
in a web application, or other software systems. It separates the release process from deployment, 
applies custom rollout strategies based in segments, allows applying instant rollbacks to failing features, 
reduces the technical debt on complex business experiments, and helps both developers and managers building trust 
between them.

## What do we need?

This is our open roadmap, here are listed our current work in progress, todos, and general project development status.
In the next [milestones](https://github.com/pheature-flags/pheature-flags/milestones), you can find the more important things where you can contribute, also we have created an [open kanban board](https://github.com/pheature-flags/pheature-flags/projects/1) where are every [issue](https://github.com/pheature-flags/pheature-flags/issues) and each status.
Please check out our [contribution guidelines](https://github.com/pheature-flags/pheature-flags/blob/main/CONTRIBUTING.md) to help us in any way, and don't hesitate to ask everything, 
we are willing to hear you.

## Milestones

**Milestone:** [Toggle management system](https://github.com/pheature-flags/pheature-flags/milestone/1)

> The toggle system allows both developers and managers to set up features enabled or disabled, and applying 
> different rollout strategies based on segmentation and environments.

- [ ] [#1](https://github.com/pheature-flags/pheature-flags/issues/1): Toggle core package ![Toggle core](https://progress-bar.dev/95)
- [ ] [#2](https://github.com/pheature-flags/pheature-flags/issues/2): Toggle model package ![Toggle model](https://progress-bar.dev/90)
- [ ] [#3](https://github.com/pheature-flags/pheature-flags/issues/3): In Memory toggle package ![In Memory toggle](https://progress-bar.dev/70)
- [ ] [#4](https://github.com/pheature-flags/pheature-flags/issues/4): Toggle CRUD package ![Toggle CRUD](https://progress-bar.dev/90)
- [ ] [#5](https://github.com/pheature-flags/pheature-flags/issues/5): Toggle API package ![Toggle API](https://progress-bar.dev/85)
- [ ] [#9](https://github.com/pheature-flags/pheature-flags/issues/9): Toggle UI ![Toggle UI](https://progress-bar.dev/60)
- [ ] [#7](https://github.com/pheature-flags/pheature-flags/issues/7): Toggle Event-Sourced package ![Event-Sourced Toggle](https://progress-bar.dev/0)
- [ ] [#6](https://github.com/pheature-flags/pheature-flags/issues/6): DBal toggle package ![In Memory toggle](https://progress-bar.dev/80)
- [ ] [#8](https://github.com/pheature-flags/pheature-flags/issues/8): Toggle Cache package ![Toggle cache](https://progress-bar.dev/0)

**Milestone:** [Client API](https://github.com/pheature-flags/pheature-flags/milestone/2)

> Crazy fast Client API, gets enabled and disabled features for each user in a system. 

- [ ] [#11](https://github.com/pheature-flags/pheature-flags/issues/11): REST API
- [ ] [#12](https://github.com/pheature-flags/pheature-flags/issues/12): Async server
- [ ] [#13](https://github.com/pheature-flags/pheature-flags/issues/13): Client traffic Event-store

**Milestone:** [SDKs](https://github.com/pheature-flags/pheature-flags/milestone/3)

> Integrate Pheature flags in any distributed software system.

- [ ] [#14](https://github.com/pheature-flags/pheature-flags/issues/14): PHP SKD
- [ ] [#15](https://github.com/pheature-flags/pheature-flags/issues/15): Node SDK
- [ ] [#16](https://github.com/pheature-flags/pheature-flags/issues/16): Vanilla JS SDK
- [ ] [#17](https://github.com/pheature-flags/pheature-flags/issues/17): Android SDK
- [ ] [#18](https://github.com/pheature-flags/pheature-flags/issues/18): IOS SDK

**Milestone:** [Community packages](https://github.com/pheature-flags/pheature-flags/milestone/4)

> Use Pheature flags out of the box in your favorite PHP framework.

- [ ] [#19](https://github.com/pheature-flags/pheature-flags/issues/19): Standalone Prototype
- [ ] [#20](https://github.com/pheature-flags/pheature-flags/issues/20): Laravel Package
- [ ] [#21](https://github.com/pheature-flags/pheature-flags/issues/21): Laravel Prototype
- [ ] [#22](https://github.com/pheature-flags/pheature-flags/issues/22): Symfony Bundle
- [ ] [#23](https://github.com/pheature-flags/pheature-flags/issues/23): Symfony Prototype
- [ ] [#24](https://github.com/pheature-flags/pheature-flags/issues/24): Laminas and Mezzio package
- [ ] [#25](https://github.com/pheature-flags/pheature-flags/issues/25): Laminas and Mezzio Prototypes
